#####################################################################
# This is Jekyll's configuration file for this project.
#
# For more information, see the documentation:
#
#     https://jekyllrb.com/docs/configuration/
#####################################################################

# Site settings
title: The DIY Healer&rsquo;s Flea
#description: >-
#    Uncomment this text to supply a site description.
#    This text will be used in feeds and other metadata
#    throughout your site.
timezone: "America/New_York"

# Build settings
markdown: kramdown
exclude: [
    "vendor",
    "README.md"
]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default

# Start and end times for the next event, used throughout the
# website in various areas. Please use a native Ruby format.
next_event:
  event_dt_start:     2018-06-24 15:00:00 -0400
  event_dt_end:       2018-06-24 20:00:00 -0400
  applications_open:  2018-06-01 00:00:00 -0400
  applications_close: 2018-06-20 00:00:00 -0400

payments:
  prices:
    vending:
      -
        item_name: "Small"
        item_cost: "20.00"
      -
        item_name: "Large"
        item_cost: "30.00"
  processors:
    paypal:
      user_id: emilymakesphotos@gmail.com
