#####################################################################
# This is Jekyll's configuration file for this project.
#
# For more information, see the documentation:
#
#     https://jekyllrb.com/docs/configuration/
#####################################################################

# Site settings
title: The DIY Healer&rsquo;s Flea
#description: >-
#    Uncomment this text to supply a site description.
#    This text will be used in feeds and other metadata
#    throughout your site.
timezone: "America/New_York"

# Build settings
markdown: kramdown
exclude: [
    "vendor",
    "README.md"
]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: "flyers"
    values:
      layout: flyer

# Start and end times for the next event, used throughout the
# website in various areas. Please use a native Ruby format.
next_event:
  venue:
    name:     "Trans Pecos"
    location: "915 Wyckoff Avenue, Queens, NY 11385"
    link:     "https://www.thetranspecos.com/"
    map_link: "https://www.openstreetmap.org/node/5364903172"
    twitter:  "thetranspecos"
  dt_start:           2018-07-28 13:00:00 -0400
  dt_end:             2018-07-28 18:00:00 -0400
  applications_open:  2018-06-25 00:00:00 -0400
  applications_close: 2018-07-14 00:00:00 -0400

payments:
  prices:
    vending:
      -
        item_name: "Vending space"
        item_cost: "45.00"
  processors:
    paypal:
      user_id: emilymakesphotos@gmail.com

category_whitelist:
  - "Apparel"
  - "Art"
  - "Bath products"
  - "Dentistry"
  - "Electronics"
  - "Food"
  - "Fragrances"
  - "Grooming"
  - "Herbal remedies"
  - "Hygiene"
  - "Jewelry"
  - "Literature"
  - "Nutrition"
  - "Perfumes"
  - "Skincare"
  - "Synthesized medication"
